<?php
/**
 * @OA\Schema(
 *     title="CreateOrganizeRow",
 *     description="CreateOrganizeRow API",
 *     @OA\Xml(
 *         name="CreateOrganizeRow"
 *     )
 * )
 */

interface CreateOrganizeRow
{
    /**
     *                     @OA\Property(
     *                           title="plan_details_id",
     *                           property="plan_details_id",
     *                           description="plan_details_id",
     *                           type="integer",
     *                           example=1
     *                      ),
     *                      @OA\Property(
     *                           title="procurement_plan_id",
     *                           property="procurement_plan_id",
     *                           description="procurement_plan_id",
     *                           type="integer",
     *                           example=1
     *                      ),
 *                          @OA\Property(
     *                           title="organize_id",
     *                           property="organize_id",
     *                           description="organize_id",
     *                           type="integer",
     *                           example=1
     *                      ),
 *                          @OA\Property(
     *                           title="count",
     *                           property="count",
     *                           description="count",
     *                           type="integer",
     *                           example=1
     *                      ),
 *                          @OA\Property(
     *                           title="supply",
     *                           property="supply",
     *                           description="supply",
     *                           type="integer",
     *                           example=1
     *                      ),
 *                          @OA\Property(
     *                           title="supply_date",
     *                           property="supply_date",
     *                           description="supply_date",
     *                           type="integer",
     *                           example=1
     *                      ),
     *                     @OA\Property(
     *                           title="is_main_tool",
     *                           property="is_main_tool",
     *                           description="Հիմնական միջոց հանդիսացող",
     *                           type="integer",
     *                           enum={"0","1"},
     *                           example=1
     *                      ),
     *                     @OA\Property(
     *                           title="is_collateral_requirement",
     *                           property="is_collateral_requirement",
     *                           description="Հայտի ապահովման ներկայացման պահանջը",
     *                           type="integer",
     *                           enum={"0","1"},
     *                           example=1
     *                      ),
     *                     @OA\Property(
     *                           title="is_product_info",
     *                           property="is_product_info",
     *                           description="Մասնակցի կողմից առաջարկվող ապրանքի, ապրանքային նշանի, ֆիրմային անվանման, մակնիշի և արտադրողի անվանման և ծագման երկրի վերաբերյալ տեղեկատվության ներկայացում Նշել բոլորը",
     *                           type="integer",
     *                           enum={"0","1"},
     *                           example=1
     *                      ),
     *                      @OA\Property(
     *                           title="shipping_address",
     *                           property="shipping_address",
     *                           description="Մատակարարման հասցեն",
     *                           example={"hy":"name","ru":"name"}
     *                      ),
     *             @OA\Property(
        *                property="percent",
        *                title="percent",
        *				   	@OA\Property(
        *				   	     title="organize_row_id",
        *				   	     property="organize_row_id",
        *				   	     description="organize_row_id",
        *				   	     type="integer",
        *				   	     example=1
        *				   	),
        *				   	@OA\Property(
        *				   	      title="name",
        *				   	      property="name",
        *				   	      description="name",
        *				   	      type="string",
        *				   	      example="name"
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_1",
        *				   	      property="month_1",
        *				   	      description="month_1",
        *				   	      type="float",
        *				   	      example=20
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_2",
        *				   	      property="month_2",
        *				   	      description="month_2",
        *				   	      type="float",
        *				   	      example=20
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_3",
        *				   	      property="month_3",
        *				   	      description="month_3",
        *				   	      type="float",
        *				   	      example=20
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_4",
        *				   	      property="month_4",
        *				   	      description="month_4",
        *				   	      type="float",
        *				   	      example=20
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_5",
        *				   	      property="month_5",
        *				   	      description="month_5",
        *				   	      type="float",
        *				   	      example=30
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_6",
        *				   	      property="month_6",
        *				   	      description="month_6",
        *				   	      type="float",
        *				   	      example=40
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_7",
        *				   	      property="month_7",
        *				   	      description="month_7",
        *				   	      type="float",
        *				   	      example=50
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_8",
        *				   	      property="month_8",
        *				   	      description="month_8",
        *				   	      type="float",
        *				   	      example=60
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_9",
        *				   	      property="month_9",
        *				   	      description="month_9",
        *				   	      type="float",
        *				   	      example=70
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_10",
        *				   	      property="month_10",
        *				   	      description="month_10",
        *				   	      type="float",
        *				   	      example=80
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_11",
        *				   	      property="month_11",
        *				   	      description="month_11",
        *				   	      type="float",
        *				   	      example=90
        *				   	 ),
        *				   	@OA\Property(
        *				   	      title="month_12",
        *				   	      property="month_12",
        *				   	      description="month_12",
        *				   	      type="float",
        *				   	      example=100
        *				   	)
        *             ),
     *
     */


}
